name: play_lab
description: A new Flutter project.
publish_to: 'none'

#Platform  Firebase App Id
#Android   1:478780527317:android:354bc924f271095fa3485c
#IOS       1:478780527317:ios:a4dd9a516223ecd9a3485c


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  

dependencies:  

  flutter:
    sdk: flutter
  esewa_flutter_sdk:
    path: ./external_sdk\eSewa Flutter Sdk v2.5.3_23\esewa_flutter_sdk
  google_sign_in: ^6.2.2
  cached_network_image: ^3.3.1
  readmore: ^3.0.0
  whitecodel_reels: ^0.0.6
  get: ^4.6.6
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.1
  country_picker: ^2.0.25
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
  flutter_widget_from_html: ^0.15.2
  flutter_inappwebview: ^6.1.0
  chewie: ^1.8.5
  shimmer: ^3.0.0
  path_provider: ^2.0.14
  flutter_staggered_animations: ^1.1.1
  flutter_local_notifications: ^17.2.2
  awesome_dialog: ^3.0.2
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5
  # flutter_facebook_auth: ^7.1.0
  google_mobile_ads: ^5.1.0
  # pay: ^3.0.1
  flutter_cache_manager: ^3.4.1
  cool_dropdown: ^2.1.0
  pusher_channels_flutter: ^2.2.0
  flutter_animate: ^4.5.0
  package_info_plus: ^8.0.2
  html: ^0.15.4
  file_picker: ^8.0.7
  image_picker: ^1.0.7
  in_app_purchase: ^3.1.13
  dio: ^5.6.0
  another_flushbar: ^1.12.30
  in_app_purchase_storekit: any
  # flutter_exit_app: ^1.1.2
  zoom_tap_animation: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  card_swiper: ^3.0.1
  visibility_detector: ^0.4.0+2
  tapped: ^2.0.0
  webview_flutter: any
  octo_image: any

  video_player: any
  rive: ^0.13.20
  wakelock_plus: ^1.3.3
 
  
dependency_overrides:
  intl: any
  http: any
  # pusher_channels_flutter:
    # git:
    #   url: https://github.com/ArmanKT/pusher-channels-flutter.git
    #   ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/social/
    - assets/animation/
    - assets/
    # - assets/mock_dashboard.json

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700

